############################################################
# +------------------------------------------------------+ #
# |                      LinLevels                       | #
# +------------------------------------------------------+ #
############################################################

# LinLevels message format
Format:
  # Plugin name in chat MC color codes supported
  PluginName: '&5[&aLinLevels&5]'
  Message:
    info: '&6'
    warn: '&c'

