name: LinLevels
version: 1.0
description: Custom level plugin

main: me.jacklin213.linlevels.LinLevels
author: jacklin213

commands:
  linlevels:
    description: Main command
    
permissions:
  linlevel.reload:
    default: op
    description: Allows config reload
  linlevel.set:
    default: op
    description: Allows Player config editing